xtensa: Prepare the transition from Reload to LRA
On 2022/10/16 14:03, Max Filippov wrote:
> Hi Suwa-san,
Hi!

> This change results in a few new regressions in the following tests caused by ICE even when running without -mlra option:
>
> +FAIL: gcc.c-torture/execute/pr92904.c   -O1  (internal compiler error: in extract_insn, at recog.cc:2791)
>
> The backtraces look like this in all of them:
>
> gcc/gcc/testsuite/gcc.c-torture/execute/pr92904.c:395:1: error:
> unrecognizable insn:
> (insn 10501 7 10502 2 (set (reg:SI 5913)
>        (const_int 1431655765 [0x55555555]))
> "gcc/gcc/testsuite/gcc.c-torture/execute/pr92904.c":239:9 -1
>     (nil))
> during RTL pass: subreg3
> gcc/gcc/testsuite/gcc.c-torture/execute/pr92904.c:395:1: internal compiler error: in extract_insn, at recog.cc:2791

"expand" pass generates the below from referencing to the struct:

  ;; MEM <long long int> [(union Y *)&u] = 6148914691236517205;
  (set (reg:DI X) (mem:DI (symbol_ref:SI ("*.LC_u"))))

and then "fwprop1" transforms it by dereference:

  (set (reg:DI X) (const_int 0x5555555555555555))

finally "subreg3" (but not "split1") splits it into the two that don't satisfy the constraint:

  (set (reg:SI X0) (const_int 0x55555555))
  (set (reg:SI X1) (const_int 0x55555555))

> There's also the following runtime failures, but only on call0 configuration:
>
> +FAIL: gcc.c-torture/execute/20010122-1.c   -O1  execution test
> +FAIL: gcc.c-torture/execute/20010122-1.c   -O2  execution test
> +FAIL: gcc.c-torture/execute/20010122-1.c   -O3 -g  execution test
> +FAIL: gcc.c-torture/execute/20010122-1.c   -Os  execution test
> +FAIL: gcc.c-torture/execute/20010122-1.c   -O2 -flto -fno-use-linker-plugin -flto-partition=none  execution test

both assembler outputs with and without this patch are identical on my side, but perhaps it can break runtime init and/or libraries due to my silly mistake:

-+      if (HARD_REGISTER_P (x)
++      if (! HARD_REGISTER_P (x)

===
This patch provides the first step in the transition from Reload to LRA
in Xtensa.

gcc/ChangeLog:

	* config/xtensa/xtensa-proto.h
	(xtensa_split1_finished_p, xtensa_split_DI_reg_imm): New prototypes.
	* config/xtensa/xtensa.cc
	(xtensa_split1_finished_p, xtensa_split_DI_reg_imm, xtensa_lra_p):
	New functions.
	(TARGET_LRA_P): Replace the dummy hook with xtensa_lra_p.
	(xt_true_regnum): Rework.
	* gcc/config/xtensa/xtensa.h (CALL_REALLY_USED_REGISTERS):
	Rename from CALL_USED_REGISTERS, and remove what correspond to
	FIXED_REGISTERS.
	* gcc/config/xtensa/constraints.md (Y):
	Use !xtensa_split1_finished_p() instead of can_create_pseudo_p().
	* gcc/config/xtensa/predicates.md (move_operand): Ditto.
	* gcc/config/xtensa/xtensa.md: Add two new split patterns:
	  - splits DImode immediate load into two SImode ones
	  - puts out-of-constraint SImode constants into the constant pool
	* gcc/config/xtensa/xtensa.opt (-mlra): New target-specific option
	for testing purpose.