libstdc++: Address '-Wunused-function' for 'print_raw'
Per recent
commit r13-3303-gcf0b7e9787c3686c47219a725f2cbcaa19faaaca
"libstdc++: Simplify print_raw function for debug assertions":

> Replace two uses of print_raw where it's clearer to just use fprintf
> directly. Then the only remaining use of print_raw is as the print_func
> argument of pretty_print.

But that one is only compiled '#if _GLIBCXX_HAVE_STACKTRACE'.
In a '--enable-werror' build I've thus run into:

    [...]/source-gcc/libstdc++-v3/src/c++11/debug.cc:613:3: error: ‘void {anonymous}::print_raw(PrintContext&, const char*, ptrdiff_t)’ defined but not used [-Werror=unused-function]
      613 |   print_raw(PrintContext& ctx, const char* str, ptrdiff_t nbc)
          |   ^~~~~~~~~
    cc1plus: all warnings being treated as errors

	libstdc++-v3/
	* src/c++11/debug.cc (print_raw): Only '#if _GLIBCXX_HAVE_STACKTRACE'.